apiVersion: v1
kind: ServiceAccount
metadata:
  name: zamaz-api-sa
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    spire.io/trust-domain: "zamaz.local"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zamaz-frontend-sa
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zamaz-api-role
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zamaz-api-rolebinding
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
subjects:
- kind: ServiceAccount
  name: zamaz-api-sa
  namespace: zamaz
roleRef:
  kind: Role
  name: zamaz-api-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zamaz-frontend-role
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["zamaz-frontend-config"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zamaz-frontend-rolebinding
  namespace: zamaz
  labels:
    app.kubernetes.io/name: zamaz
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: zamaz-platform
    app.kubernetes.io/managed-by: kustomize
subjects:
- kind: ServiceAccount
  name: zamaz-frontend-sa
  namespace: zamaz
roleRef:
  kind: Role
  name: zamaz-frontend-role
  apiGroup: rbac.authorization.k8s.io