apiVersion: v1
kind: ConfigMap
metadata:
  name: zamaz-frontend-config
data:
  # Development frontend configuration
  NODE_ENV: "development"
  
  # Enable all development features
  REACT_APP_ENABLE_DEVTOOLS: "true"
  REACT_APP_ENABLE_NOTIFICATIONS: "true"
  REACT_APP_ENABLE_ANALYTICS: "false"
  REACT_APP_ENABLE_DEBUG: "true"
  REACT_APP_ENABLE_HOT_RELOAD: "true"
  
  # Development API endpoint
  REACT_APP_API_URL: "http://dev-zamaz-api-service.zamaz-dev.svc.cluster.local:8080"
  REACT_APP_WS_URL: "ws://dev-zamaz-api-service.zamaz-dev.svc.cluster.local:8080/ws"
  
  # Relaxed security for development
  REACT_APP_AUTH_DOMAIN: "dev.zamaz.local"
  REACT_APP_SESSION_STORAGE: "localStorage"