apiVersion: apps/v1
kind: Deployment
metadata:
  name: zamaz-frontend-deployment
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: NODE_ENV
          value: "development"
        - name: API_BASE_URL
          value: "http://dev-zamaz-api-service:8080"
        - name: ENABLE_HOT_RELOAD
          value: "true"
        - name: ENABLE_DEVTOOLS
          value: "true"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5