apiVersion: apps/v1
kind: Deployment
metadata:
  name: zamaz-api-deployment
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_MODE
          value: "true"
        - name: ENABLE_PPROF
          value: "true"
        - name: PERFORMANCE_PROFILING
          value: "true"
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5