apiVersion: apps/v1
kind: Deployment
metadata:
  name: zamaz-app
spec:
  template:
    spec:
      containers:
      - name: zamaz
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DEBUG
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zamaz-frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENVIRONMENT
          value: "staging"