apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zamaz-staging

bases:
- ../../base

commonLabels:
  environment: staging

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

configMapGenerator:
- name: zamaz-config
  behavior: merge
  literals:
  - app.env=staging
  - log.level=debug
  - node.env=staging
  - api.url=http://zamaz-api:8080

secretGenerator:
- name: zamaz-secrets
  behavior: replace
  literals:
  - database.url=postgresql://zamaz_staging:staging_pass@localhost:5432/zamaz_staging
  - jwt.secret=staging-jwt-secret-key-for-development-only
  type: Opaque

# Use local/latest images for staging
images:
- name: zamaz
  newName: zamaz-server
  newTag: latest
- name: zamaz-frontend
  newName: zamaz-frontend
  newTag: latest

replicas:
- name: zamaz-app
  count: 1
- name: zamaz-frontend
  count: 1