services:
  # PostgreSQL for database integration tests
  postgres:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_DB: mvp_db
      POSTGRES_USER: mvp_user
      POSTGRES_PASSWORD: mvp_pass
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mvp_user -d mvp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NATS for messaging integration tests
  nats:
    image: nats:latest
    platform: linux/amd64
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--store_dir", "/data"]
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching integration tests
  redis:
    image: redis:7
    platform: linux/amd64
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nats-data: