services:
  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    restart: unless-stopped
    ports:
      - "5678:8080"
    environment:
      - BB_SERVER_ADDRESS=0.0.0.0
      - BB_PORT=8080
      - BB_DATA=/var/opt/bytebase
      - BB_EXTERNAL_URL=http://localhost:5678
      - BB_DEBUG=false
      - BB_DEMO=false
      - BB_READONLY=false
      - BB_DISABLE_SIGNUP=false
    volumes:
      - ./bytebase/data:/var/opt/bytebase
      - ./db/migrations:/migrations:ro
    networks:
      - bytebase-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  bytebase-network:
    driver: bridge
