services:
  # PostgreSQL for database integration tests
  postgres:
    image: postgres:15-alpine
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    environment:
      POSTGRES_DB: mvp_db
      POSTGRES_USER: mvp_user
      POSTGRES_PASSWORD: mvp_password
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mvp_user -d mvp_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mvp-test-network

  # NATS for messaging integration tests
  nats:
    image: nats:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--store_dir", "/data"]
    volumes:
      - nats-data:/data
    networks:
      - mvp-test-network

  # Redis for caching integration tests
  redis:
    image: redis:7
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mvp-test-network

volumes:
  nats-data:

networks:
  mvp-test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24