# External Secrets Operator configuration for production secrets
# This pulls secrets from AWS Secrets Manager / HashiCorp Vault / etc.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: zero-trust-secret-store
  namespace: zero-trust-prod
spec:
  provider:
    # AWS Secrets Manager example (adjust for your provider)
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key
---
# Keycloak External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: zero-trust-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zero-trust-secret-store
    kind: SecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: zero-trust/prod/keycloak/admin-password
    - secretKey: DB_PASSWORD
      remoteRef:
        key: zero-trust/prod/keycloak/db-password
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: zero-trust/prod/keycloak/client-secret
---
# OPA External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opa-secrets
  namespace: zero-trust-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zero-trust-secret-store
    kind: SecretStore
  target:
    name: opa-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPA_DB_PASSWORD
      remoteRef:
        key: zero-trust/prod/opa/db-password
    - secretKey: BUNDLE_SERVICE_TOKEN
      remoteRef:
        key: zero-trust/prod/opa/bundle-token
---
# Backend API External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: zero-trust-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zero-trust-secret-store
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: zero-trust/prod/backend/jwt-signing-key
    - secretKey: DATABASE_URL
      remoteRef:
        key: zero-trust/prod/backend/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: zero-trust/prod/backend/redis-url
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: zero-trust/prod/backend/encryption-key
---
# TLS Certificate External Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls-certificates
  namespace: zero-trust-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: zero-trust-secret-store
    kind: SecretStore
  target:
    name: zero-trust-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: zero-trust/prod/tls/fullchain
    - secretKey: tls.key
      remoteRef:
        key: zero-trust/prod/tls/privkey