# External Secrets Operator configuration for HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: zero-trust-prod
spec:
  provider:
    vault:
      server: "https://vault.company.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "zero-trust-auth"
          serviceAccountRef:
            name: "external-secrets"

---
# Database credentials from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: zero-trust-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: database/creds/zero-trust-role
      property: username
  - secretKey: password
    remoteRef:
      key: database/creds/zero-trust-role
      property: password
  - secretKey: host
    remoteRef:
      key: secret/zero-trust/database
      property: host

---
# JWT signing keys from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-keys
  namespace: zero-trust-prod
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jwt-keys
    creationPolicy: Owner
  data:
  - secretKey: private-key
    remoteRef:
      key: secret/zero-trust/jwt
      property: private-key
  - secretKey: public-key
    remoteRef:
      key: secret/zero-trust/jwt
      property: public-key
EOF < /dev/null