{{- if .Values.prometheusRules.enabled }}
{{- if .Values.prometheusRules.zamaz.enabled }}
# PrometheusRule for Zamaz Application
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zamaz-application-rules
  namespace: {{ .Values.global.namespaces.monitoring }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: zamaz
    prometheus: kube-prometheus
spec:
  groups:
  - name: zamaz.application
    interval: 30s
    rules:
    {{- range .Values.prometheusRules.zamaz.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr | quote }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
---
{{- end }}

{{- if .Values.prometheusRules.security.enabled }}
# PrometheusRule for Security
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zamaz-security-rules
  namespace: {{ .Values.global.namespaces.monitoring }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: zamaz
    prometheus: kube-prometheus
spec:
  groups:
  - name: zamaz.security
    interval: 15s
    rules:
    {{- range .Values.prometheusRules.security.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr | quote }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
---
{{- end }}

{{- if .Values.prometheusRules.infrastructure.enabled }}
# PrometheusRule for Infrastructure
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zamaz-infrastructure-rules
  namespace: {{ .Values.global.namespaces.monitoring }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app: zamaz
    prometheus: kube-prometheus
spec:
  groups:
  - name: zamaz.infrastructure
    interval: 30s
    rules:
    {{- range .Values.prometheusRules.infrastructure.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr | quote }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
---
{{- end }}
{{- end }}