apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: platform-namespaces
  annotations:
    config.kubernetes.io/local-config: "true"

# Platform namespace resources
resources:
- namespaces.yaml

# Common labels for platform namespaces
commonLabels:
  app.kubernetes.io/part-of: zamaz-platform
  app.kubernetes.io/managed-by: kustomize
  component: platform