# AlertManager configuration for Zero Trust Authentication alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: zero-trust-prod
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: '${SLACK_API_URL}'
      pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'platform-security'
      routes:
      # Critical alerts go to PagerDuty and Slack
      - match:
          severity: critical
        receiver: 'critical-alerts'
        continue: true
      # Compliance alerts have special handling
      - match:
          compliance: required
        receiver: 'compliance-alerts'
        repeat_interval: 1h
      # SLO violations
      - match:
          slo: true
        receiver: 'slo-alerts'
        repeat_interval: 30m

    receivers:
    - name: 'platform-security'
      slack_configs:
      - channel: '#platform-security-alerts'
        title: 'Zero Trust Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
        actions:
        - type: button
          text: 'Runbook'
          url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
        - type: button
          text: 'Dashboard'
          url: 'https://grafana.company.com/d/zero-trust-auth'

    - name: 'critical-alerts'
      pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ (index .Alerts 0).Annotations.summary }}'
        details:
          severity: '{{ (index .Alerts 0).Labels.severity }}'
          alertname: '{{ (index .Alerts 0).Labels.alertname }}'
      slack_configs:
      - channel: '#platform-security-critical'
        username: 'Zero Trust Critical Alert'
        color: 'danger'
        title: '🚨 CRITICAL: {{ (index .Alerts 0).Labels.alertname }}'
        text: '{{ (index .Alerts 0).Annotations.description }}'
        send_resolved: true

    - name: 'compliance-alerts'
      email_configs:
      - to: 'compliance-team@company.com'
        from: 'zero-trust-alerts@company.com'
        smarthost: 'smtp.company.com:587'
        auth_username: '${SMTP_USERNAME}'
        auth_password: '${SMTP_PASSWORD}'
        headers:
          Subject: 'Zero Trust Compliance Alert: {{ (index .Alerts 0).Labels.alertname }}'
        html: |
          <h2>Compliance Alert</h2>
          <p><strong>Alert:</strong> {{ (index .Alerts 0).Labels.alertname }}</p>
          <p><strong>Description:</strong> {{ (index .Alerts 0).Annotations.description }}</p>
          <p><strong>Policy:</strong> {{ (index .Alerts 0).Labels.policy }}</p>
          <p><strong>Time:</strong> {{ (index .Alerts 0).StartsAt }}</p>
      slack_configs:
      - channel: '#compliance-alerts'
        username: 'Compliance Bot'
        color: 'warning'
        title: '⚖️ Compliance Alert'
        text: '{{ (index .Alerts 0).Annotations.description }}'

    - name: 'slo-alerts'
      slack_configs:
      - channel: '#platform-slo-alerts'
        username: 'SLO Bot'
        color: 'warning'
        title: '📊 SLO Violation'
        text: |
          *Service:* {{ (index .Alerts 0).Labels.job }}
          *Metric:* {{ (index .Alerts 0).Labels.alertname }}
          *Current Value:* {{ (index .Alerts 0).Annotations.description }}
          *Dashboard:* https://grafana.company.com/d/zero-trust-auth

    inhibit_rules:
    # Inhibit non-critical alerts when service is down
    - source_match:
        alertname: 'KeycloakDown'
      target_match_re:
        alertname: '.*'
      equal: ['service']
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'service']

    templates:
    - '/etc/alertmanager/templates/*.tmpl'
---
# Notification templates
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: zero-trust-prod
data:
  zero-trust.tmpl: |
    {{ define "zero_trust.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
    {{ end }}

    {{ define "zero_trust.text" }}
    {{ range .Alerts }}
    *Alert:* {{ .Labels.alertname }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Service:* {{ .Labels.service }}
    *Started:* {{ .StartsAt }}
    {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|View Runbook>{{ end }}
    {{ end }}
    {{ end }}