apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zamaz.fullname" . }}-config
  labels:
    {{- include "zamaz.labels" . | nindent 4 }}
data:
  app.env: {{ .Values.config.environment | default "development" | quote }}
  log.level: {{ .Values.config.logLevel | default "info" | quote }}
  node.env: {{ .Values.config.environment | default "development" | quote }}
  api.url: "http://{{ include "zamaz.fullname" . }}-api:8080"