apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zamaz.fullname" . }}-secret
  labels:
    {{- include "zamaz.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ "postgresql://user:pass@localhost:5432/zamaz" | b64enc | quote }}
  redis-url: {{ "redis://localhost:6379" | b64enc | quote }}
  jwt-secret: {{ "demo-jwt-secret-key-change-in-production" | b64enc | quote }}