global:
  resolve_timeout: 5m

route:
  receiver: default
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: default
    slack_configs:
      - api_url: $SLACK_WEBHOOK_URL
        channel: '#alerts'
        send_resolved: true

