apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zamaz-app-pdb
  labels:
    app: zamaz
    component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zamaz
      component: api
  unhealthyPodEvictionPolicy: AlwaysAllow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zamaz-frontend-pdb
  labels:
    app: zamaz
    component: frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: zamaz
      component: frontend
  unhealthyPodEvictionPolicy: AlwaysAllow