# External Secrets configuration for secure secrets management
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: zamaz-prod
spec:
  provider:
    vault:
      server: "https://vault.company.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "zamaz-app"
          serviceAccountRef:
            name: "zamaz-external-secrets"
---
# AWS Secrets Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: zamaz-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: "zamaz-external-secrets"
---
# Google Secret Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: zamaz-prod
spec:
  provider:
    gcpsm:
      projectId: "your-gcp-project"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: zamaz-cluster
          serviceAccountRef:
            name: "zamaz-external-secrets"
---
# Azure Key Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: zamaz-prod
spec:
  provider:
    azurekv:
      vaultUrl: "https://zamaz-vault.vault.azure.net/"
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: "zamaz-external-secrets"