# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zamaz-external-secrets
  namespace: zamaz-prod
  annotations:
    # AWS IRSA annotation
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/zamaz-external-secrets-role
    # Azure Workload Identity annotation  
    azure.workload.identity/client-id: "client-id-here"
    # GCP Workload Identity annotation
    iam.gke.io/gcp-service-account: zamaz-external-secrets@PROJECT-ID.iam.gserviceaccount.com
---
# ClusterRole for External Secrets access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zamaz-external-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets", "secretstores", "clustersecretstores"]
  verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for External Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zamaz-external-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zamaz-external-secrets-role
subjects:
- kind: ServiceAccount
  name: zamaz-external-secrets
  namespace: zamaz-prod
---
# Role for namespace-specific access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: zamaz-prod
  name: zamaz-external-secrets-namespace-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets", "secretstores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# RoleBinding for namespace access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zamaz-external-secrets-namespace-binding
  namespace: zamaz-prod
subjects:
- kind: ServiceAccount
  name: zamaz-external-secrets
  namespace: zamaz-prod
roleRef:
  kind: Role
  name: zamaz-external-secrets-namespace-role
  apiGroup: rbac.authorization.k8s.io