{{- if .Values.serviceSecurity.enabled }}
{{- range .Values.serviceSecurity.serviceAccounts }}
# Service Account: {{ .name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "security-policies.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}

{{- range .Values.serviceSecurity.rbac }}
# Role: {{ .name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "security-policies.labels" $ | nindent 4 }}
rules:
  {{- toYaml .rules | nindent 2 }}
---
# RoleBinding: {{ .name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ .namespace }}
  labels:
    {{- include "security-policies.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name }}
subjects:
- kind: ServiceAccount
  name: {{ .serviceAccount }}
  namespace: {{ .namespace }}
---
{{- end }}
{{- end }}