{{- if .Values.networkPolicy.enabled }}
{{- range .Values.networkPolicy.policies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "istio-mesh.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
---
{{- end }}
{{- end }}