[book]
title = "Zamaz Zero Trust Platform Documentation"
authors = ["Zamaz Development Team"]
description = "Comprehensive documentation for the Zamaz Zero Trust Authentication Platform with Service Discovery, Istio Service Mesh, and Modern CI/CD"
src = "src"
language = "en"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "coal"
curly-quotes = true
mathjax-support = false
copy-fonts = true
google-analytics = ""
additional-css = ["theme/custom.css"]
additional-js = []
no-section-label = false
git-repository-url = "https://github.com/zamaz/root-zamaz"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/zamaz/root-zamaz/edit/main/docs-book/src/{path}"
site-url = "/docs/"
cname = ""
input-404 = "404.md"

[output.html.print]
enable = true
page-break = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = false
runnable = false

[output.html.code]
hidelines = ""

[output.html.fold]
enable = true
level = 0

# Preprocessors
[preprocessor.links]
# Built-in link preprocessor

[preprocessor.index]
# Built-in index preprocessor

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

# Custom theme and styling
[output.html.theme]
favicon-svg = "images/favicon.svg"
favicon-png = "images/favicon.png"

# Custom variables for templating
[output.html.custom]
company = "Zamaz"
product = "Zero Trust Platform"
version = "v1.0.0"
support-email = "support@zamaz.io"

# GitBook-style configuration
[rust]
edition = "2021"
