apiVersion: v1
kind: ConfigMap
metadata:
  name: zamaz-config
  labels:
    app: zamaz
data:
  app.env: "development"
  log.level: "info"
  node.env: "development"
  api.url: "http://zamaz-api"
  
  # Database configuration
  database.host: "postgres"
  database.port: "5432"
  database.name: "zamaz"
  
  # Redis configuration
  redis.host: "redis"
  redis.port: "6379"
  
  # NATS configuration
  nats.url: "nats://nats:4222"
  
  # Observability configuration
  metrics.enabled: "true"
  tracing.enabled: "true"
  tracing.endpoint: "http://jaeger-collector:14268/api/traces"