apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zamaz

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: zamaz

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- rbac.yaml
- network-policy.yaml

images:
- name: zamaz
  newTag: latest
- name: zamaz-frontend
  newTag: latest

configMapGenerator:
- name: zamaz-version
  literals:
  - version=v0.1.0
  - build.date=2024-01-01

secretGenerator:
- name: zamaz-secrets
  literals:
  - database.url=postgresql://user:pass@postgres:5432/zamaz
  type: Opaque