services:
  authz:
    url: http://localhost:8181

bundles:
  authz:
    service: authz
    resource: "/policies/zero_trust_authz.rego"
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10

plugins:
  envoy_ext_authz_grpc:
    addr: :9191
    enable_reflection: true
