apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: zero-trust-production

namespace: zero-trust-prod

resources:
- ../../base
- secrets/vault-secret-store.yaml
- monitoring/prometheus-servicemonitor.yaml
- monitoring/grafana-dashboard.yaml
- backup/backup-strategy.yaml
- capacity-planning.yaml
- security/network-policies.yaml
- security/security-scanning.yaml

commonLabels:
  environment: production
  app.kubernetes.io/part-of: zero-trust-auth

replicas:
- name: keycloak
  count: 3
- name: opa
  count: 3
- name: backend-api
  count: 5

configMapGenerator:
- name: production-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
  - METRICS_ENABLED=true

images:
- name: keycloak
  newTag: 23.0.4
- name: openpolicyagent/opa
  newTag: 0.58.0-envoy
- name: zero-trust-backend
  newTag: v1.0.0