apiVersion: v1
kind: Namespace
metadata:
  name: zero-trust-prod
  labels:
    name: zero-trust-prod
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    zero-trust.io/description: "Production namespace for Zero Trust Authentication System"
    zero-trust.io/owner: "platform-security@company.com"
---
# Resource quota for production namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: zero-trust-prod-quota
  namespace: zero-trust-prod
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "20"
    services.loadbalancers: "5"
---
# Limit range for production pods
apiVersion: v1
kind: LimitRange
metadata:
  name: zero-trust-prod-limits
  namespace: zero-trust-prod
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4000m"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container