name: Wiki Sync

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'scripts/sync-wiki.sh'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  sync-wiki:
    name: Sync Documentation to GitHub Wiki
    runs-on: ubuntu-latest
    if: github.repository == 'zamaz/root-zamaz'  # Only run on main repo
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for commit info
        
    - name: Install jq for API calls
      run: sudo apt-get update && sudo apt-get install -y jq
        
    - name: Generate latest documentation
      run: |
        # Generate fresh documentation before syncing
        make docs-ci || echo "Documentation generation failed, using existing docs"
      env:
        DB_HOST: ${{ secrets.DB_HOST || 'localhost' }}
        DB_PORT: ${{ secrets.DB_PORT || '5432' }}
        DB_NAME: ${{ secrets.DB_NAME || 'mvp_db' }}
        DB_USER: ${{ secrets.DB_USER || 'mvp_user' }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'mvp_password' }}
        
    - name: Sync to GitHub Wiki
      run: |
        ./scripts/sync-wiki-api.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}

  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: sync-wiki
    if: success()
    
    steps:
    - name: Wiki sync notification
      run: |
        echo "✅ Wiki sync completed successfully"
        echo "📍 Wiki available at: https://github.com/${{ github.repository }}/wiki"